mutation CustomerLogin($input: CustomerAccessTokenCreateInput!) {
	customerAccessTokenCreate(input: $input) {
		customerAccessToken {
			accessToken
		}
		customerUserErrors {
			field
			message
		}
	}
}
