query GetCart($id: ID!) {
	cart(id: $id) {
		id
		checkoutUrl
		cost {
			totalAmount {
				amount
			}
		}
		lines(first: 50) {
			edges {
				node {
					id
					quantity
					merchandise {
						... on ProductVariant {
							id
							title
							availableForSale
							priceV2 {
								amount
							}
							product {
								id
								title
								description
								images(first: 1) {
									edges {
										node {
											originalSrc
											altText
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}
}
