query SearchGetProducts($query: String!, $first: Int) {
	search(query: $query, first: $first, types: PRODUCT) {
		edges {
			node {
				... on Product {
					id
					title
					featuredImage {
						originalSrc
						altText
					}
				}
			}
		}
	}
}
