query GetProduct($id: ID!) {
	product(id: $id) {
		id
		title
		description
		totalInventory
		priceRange {
			maxVariantPrice {
				amount
			}
			minVariantPrice {
				amount
			}
		}
		variants(first: 10) {
			edges {
				node {
					id
					title
					priceV2 {
						amount
					}
					availableForSale
					selectedOptions {
						name
						value
					}
					product {
						id
						title
						description
						images(first: 10) {
							edges {
								node {
									originalSrc
									altText
								}
							}
						}
					}
				}
			}
		}
	}
}
