query GetProducts {
	products(first: 20) {
		edges {
			node {
				id
				title
				description
				totalInventory
				featuredImage {
					url
				}
				priceRange {
					maxVariantPrice {
						amount
					}
					minVariantPrice {
						amount
					}
				}
			}
		}
	}
}
