mutation LogoutCustomer($accessToken: String!) {
	customerAccessTokenDelete(customerAccessToken: $accessToken) {
		deletedAccessToken
		deletedCustomerAccessTokenId
		userErrors {
			field
			message
		}
	}
}
